ALTER TABLE candidates ADD COLUMN IF NOT EXISTS ai_score INTEGER;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS ai_analysis TEXT;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS ai_status VARCHAR(50) DEFAULT 'pending';
